site_name: cu - ClickUp CLI
site_url: https://timimsms.github.io/cu
repo_url: https://github.com/timimsms/cu
repo_name: timimsms/cu
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

nav:
  - Home: index.md
  - Commands:
    - cu: commands/cu.md
    - Authentication:
      - cu auth: commands/cu_auth.md
      - cu auth login: commands/cu_auth_login.md
      - cu auth logout: commands/cu_auth_logout.md
      - cu auth status: commands/cu_auth_status.md
    - Tasks:
      - cu task: commands/cu_task.md
      - cu task create: commands/cu_task_create.md
      - cu task list: commands/cu_task_list.md
      - cu task view: commands/cu_task_view.md
      - cu task update: commands/cu_task_update.md
      - cu task close: commands/cu_task_close.md
      - cu task reopen: commands/cu_task_reopen.md
      - cu task search: commands/cu_task_search.md
      - cu task interactive: commands/cu_task_interactive.md
    - Lists:
      - cu list: commands/cu_list.md
      - cu list list: commands/cu_list_list.md
      - cu list default: commands/cu_list_default.md
    - Spaces:
      - cu space: commands/cu_space.md
      - cu space list: commands/cu_space_list.md
    - Comments:
      - cu comment: commands/cu_comment.md
      - cu comment list: commands/cu_comment_list.md
      - cu comment delete: commands/cu_comment_delete.md
    - Configuration:
      - cu config: commands/cu_config.md
      - cu config init: commands/cu_config_init.md
      - cu config list: commands/cu_config_list.md
      - cu config get: commands/cu_config_get.md
      - cu config set: commands/cu_config_set.md
      - cu config show: commands/cu_config_show.md
    - Cache:
      - cu cache: commands/cu_cache.md
      - cu cache info: commands/cu_cache_info.md
      - cu cache clear: commands/cu_cache_clear.md
      - cu cache clean: commands/cu_cache_clean.md
    - Bulk Operations:
      - cu bulk: commands/cu_bulk.md
      - cu bulk update: commands/cu_bulk_update.md
      - cu bulk close: commands/cu_bulk_close.md
      - cu bulk delete: commands/cu_bulk_delete.md
    - Export:
      - cu export: commands/cu_export.md
      - cu export tasks: commands/cu_export_tasks.md
    - Users:
      - cu user: commands/cu_user.md
      - cu user list: commands/cu_user_list.md
    - Other Commands:
      - cu api: commands/cu_api.md
      - cu me: commands/cu_me.md
      - cu interactive: commands/cu_interactive.md
      - cu completion: commands/cu_completion.md
      - cu version: commands/cu_version.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/timimsms/cu

docs_dir: docs/site